language: node_js
node_js:
  - node
before_install:
  # Decrypt the private key
  - openssl aes-256-cbc -K $encrypted_49aebbe7f141_key -iv $encrypted_49aebbe7f141_iv
    -in .travis/jackklpan-hexo-blog-deploy-key.enc -out ~/.ssh/id_rsa
    -d
  # Set the permission of the key
  - chmod 600 ~/.ssh/id_rsa
  # Start SSH agent
  - eval $(ssh-agent)
  # Add the private key to the system
  - ssh-add ~/.ssh/id_rsa
  # Copy SSH config
  - cp .travis/ssh_config ~/.ssh/config
  # Set Git config
  - git config --global user.name "jackklpan"
  - git config --global user.email jackklpan@gmail.com
  # Install Hexo
  - npm install hexo -g
  # Clone the repository, 產生的檔案會放置於.deploy_git，將其clone下來使commit一致，避免git force update
  - git clone --branch gh-pages https://github.com/jackklpan/hexo-blog.git .deploy_git
script:
  - git submodule init # 用于更新主题，需要指定到自己的repo，否则会clone最新NexT主题，客製化的部分會消失
  - git submodule update
  - hexo generate
  - hexo deploy
branches:
  only:
    - master
